# Autogenerated by devscripts/update-version.py

__version__ = '2025.08.26.030753'

RELEASE_GIT_HEAD = '3bd91544122142a87863d79e54e995c26cfd7f92'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'lemon8866/yt-dlp'

ORIGIN = 'lemon8866/yt-dlp'

_pkg_version = '2025.08.26.030753'
